### ISSUE TITLE
Parse multiple vdbench Work Definitions within one output file

### ISSUE THREAD

**Issue by jmsearcy** [eric-becker/vdbench_graphite#3]
Add ability to parse data for multiple vdbench work definitions (wd's) within a single output file.

ie. running multiple tests with different block sizes

**Comment by eric-becker** [comment]
Are you looking for the ability to differentiate the ouptut from multiple wd's within the same rd?  Or simply tag multiple rd's within the same vdbench execution?  I don't believe vdbench actually breaks out different wd's in stdout, but could check into the other output files.   They don't update as frequently though. 

In any case this will likely be moved over to an effort with telegraf -> influxdb.

**Comment by phenixblue** [comment]
Thanks for the response. It's honestly been so long ago that I don't directly recall the specifics behind this. Feel free to close.

**Comment by eric-becker** [comment]
closing
