### ISSUE TITLE
vdbench workload file

### ISSUE THREAD

**Issue by claytondukes** [eric-becker/vdbench_graphite#5]
Could I get a copy of the workload definition file you used?

**Comment by eric-becker** [comment]
I'm not sure which one I used here.  Are you looking for a vdbench config file or an example of how it all runs? I could probably give you an example vdbench template if you let me know device name/paths, dedup, compression, iosize distribution, and sequal/random ratio.

**Comment by claytondukes** [comment]
Think I've gotten it figured out. I ended up writing a different script. My systems kept failing on the awk command.
